apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satellite-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "satellite-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "satellite-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "satellite-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect={{ .Values.leaderElect }}
            {{- if .Values.watchNamespace }}
            - --namespace={{ .Values.watchNamespace }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
